# Generated by Django 4.1 on 2022-08-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='validated',
            field=models.BooleanField(default=False, help_text='if it is true that means user have validate otp'),
        ),
    ]
